image: Visual Studio 2019
version: '3.1.0-build{build}'
init:
  - if %APPVEYOR_REPO_TAG%==true (appveyor UpdateBuild -Version "%APPVEYOR_BUILD_VERSION%")
skip_branch_with_pr: true
services:
  - postgresql101
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    Test__Npgsql__DefaultConnection: Host=localhost;Database=postgres;Username=postgres;Password=Password12!
    PGUSER: postgres
    PGPASSWORD: Password12!
    PGROONGA_ZIP: pgroonga-2.2.1-postgresql-10-x64.zip
    NoPackageAnalysis: true  # Suppresses warning about SemVer 2.0.0 version suffixes when packing
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - $(PGROONGA_ZIP)
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
install:
  - powershell .build\setup_appveyor.ps1
configuration: Release
before_build:
  - appveyor-retry dotnet restore -v Minimal
build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
deploy:
  - provider: NuGet
    api_key:
      secure: SkUVFaH/8bCtjorVU9YQJxMhuj1jHJSEy4VZC3FPBQTiH2rWP/dB2GNMjsr6P+LW
    on:
      branch: develop
  - provider: NuGet
    api_key:
      secure: SkUVFaH/8bCtjorVU9YQJxMhuj1jHJSEy4VZC3FPBQTiH2rWP/dB2GNMjsr6P+LW
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    description: AppVeyor CI deployment
    auth_token:
      secure: IApJWoucWEA6qjZn1atyOtaEMbBJVMcs8r4AeTwX3yOPWYK76w6VzOpzG+eTainp
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true
